version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "QuickBooks.Net.Tests" -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_ID%
- dotnet build "QuickBooks.Net.Data" -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_ID%
- dotnet build "QuickBooks.Net" -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_ID%
after_build:
- dotnet pack "QuickBooks.Net.Data" -c %CONFIGURATION% -o ../artifacts --version-suffix %APPVEYOR_BUILD_ID%
- dotnet pack "QuickBooks.Net" -c %CONFIGURATION% -o ../artifacts --version-suffix %APPVEYOR_BUILD_ID%
artifacts:
- path: artifacts\*.*

build:
  publish_nuget: true
deploy:
  provider: NuGet
  api_key:
    secure: EF8tqT6/U0vyWo4tF9h0Z8dat/h+QD9kBMgTbrM+N5QKBn06G9P7qsbvwXhI/e9R
  on:
    branch: master
  skip_symbols: true
  artifact: /.*\.nupkg/

